// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKx70I121cAybwBKPptTOGzxviAGHuAU',
    appId: '1:814997966234:web:b307367f3a64c1814a3e23',
    messagingSenderId: '814997966234',
    projectId: 'easycart-2003',
    authDomain: 'easycart-2003.firebaseapp.com',
    storageBucket: 'easycart-2003.firebasestorage.app',
    measurementId: 'G-3X09BC7XHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMxr3fvCoQhSyswdRpI7dSc0D3gkRt3Cg',
    appId: '1:814997966234:android:657de45cce1040614a3e23',
    messagingSenderId: '814997966234',
    projectId: 'easycart-2003',
    storageBucket: 'easycart-2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ke_LhmnfGaHkJjVfBp7z7FO5izdGSuo',
    appId: '1:814997966234:ios:36e393150915a2ad4a3e23',
    messagingSenderId: '814997966234',
    projectId: 'easycart-2003',
    storageBucket: 'easycart-2003.firebasestorage.app',
    iosBundleId: 'com.example.workshopShoppingApp',
  );
}
